#!/bin/sh
while getopts p:n:d: flag
do
	case "${flag}" in
		p) project=${OPTARG};;
		n) name=${OPTARG};;
		d) description=${OPTARG};;
	esac
done

if [ -z "$project" ]; then
	echo "Use -p for initialize project folder name";
	exit 0;
fi

if ! [ -x "$(command -v composer)" ]; then
	apt update
	apt install composer
fi

if ! [ -x "$(command -v git)" ]; then
	apt install git
fi

composer create-project laravel/laravel $project

cd $project/

composer require cboden/ratchet laravel-notification-channels/webpush

rm -rf app/Models/User.php
rm -rf database/migrations

git clone https://github.com/crenata/laravel-starter-kit.git

cp -rf laravel-starter-kit/. .
rm -rf laravel-starter-kit
rm -rf .git

sed -i '5i use App\\Enums\\TokenEnum;' app/Http/Kernel.php
sed -i 's+middlewareAliases = \[+middlewareAliases = \[\nTokenEnum::AUTH_ADMIN => \\App\\Http\\Middleware\\AdminMiddleware::class,\nTokenEnum::AUTH_USER => \\App\\Http\\Middleware\\UserMiddleware::class,+g' app/Http/Kernel.php

echo "WEBSOCKET_PORT=8090" | tee -a .env .env.example > /dev/null
echo "SERVER_CRT=\"/mnt/c/Xampp/apache/conf/ssl.crt/server.crt\"" | tee -a .env .env.example > /dev/null
echo "SERVER_KEY=\"/mnt/c/Xampp/apache/conf/ssl.key/server.key\"" | tee -a .env .env.example > /dev/null
echo "VAPID_PUBLIC_KEY=" | tee -a .env .env.example > /dev/null
echo "VAPID_PRIVATE_KEY=" | tee -a .env .env.example > /dev/null

php artisan webpush:vapid

if ! [ -z "$name" ]; then
	sed -i "s+Laravel+$name+g" .env
fi